# Generated by Django 5.0.7 on 2025-02-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_alter_candidate_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='varified',
            field=models.BooleanField(default=False),
        ),
    ]
